sudo: required

language:
  - cpp

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test


script:
    - mkdir build
    - cd build
    - cmake CMAkeLists.txt
    - make ./executeTests
    - ./executeTests