sudo: required

language: cpp

os:
  - linux

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake CMakeLists.txt
  - make ./executeTests
  - ./executeTests


notifications:
  email: true